#!/bin/bash
./DFA $0 $@; exit 

# the two initial lines make this file executable
# (they're optional - if the file starts with a bang, the parser will ignore the first two lines)

# this defines a state - transitions are defined below
# i marks the initial state
initial i
  a accept

# a marks accepting states
accept a
  a initial

